name: Test
on:
  push:
    paths:
      - '**.cr'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [master]
    paths:
      - '**.cr'
      - '.github/workflows/test.yml'
  schedule:
    - cron: '0 6 * * 6'
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Lint code
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        cockroachdb: ['v22.2.0', latest]
        crystal: ['1.4.0', latest]
        experimental: [false]
        include:
          - crystal: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: ~/.cache/shards
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-
      - name: Install shards
        run: shards update
      - name: Install Redis
        run: sudo apt -y install redis
      - name: Start Redis
        run: sudo systemctl start redis
      - name: Install Postgresql
        run: |
          sudo apt update
          sudo apt -y install postgresql
      - name: Start Postgresql
        run: sudo systemctl start postgresql
      - name: Set Postgres password
        run: >-
          sudo -u postgres psql -c
          "ALTER USER postgres WITH PASSWORD 'password';"
      - name: Install CockroachDB
        run: |
          sudo apt update
          sudo apt -y install tar wget
          sudo mkdir -p /usr/local/lib/cockroach
          wget -O cockroachdb.tgz https://binaries.cockroachdb.com/cockroach-${{ matrix.cockroachdb }}.linux-amd64.tgz
          tar -xzf cockroachdb.tgz
          sudo cp -f cockroach-*/cockroach /usr/local/bin/
          sudo chmod +x /usr/local/bin/cockroach
          sudo cp -rf cockroach-*/lib/* /usr/local/lib/cockroach/
        working-directory: /tmp
      - name: Start CockroachDB
        run: cockroach start-single-node --insecure --listen-addr=localhost:36257 --sql-addr=localhost:26257 --background
      - name: Run tests
        env:
          COCKROACH_URL: postgres://root@localhost:26257/dude_spec?sslmode=disable
          POSTGRES_URL: postgres://postgres:password@localhost:5432/dude_spec
          REDIS_URL: redis://localhost:6379/0
        run: crystal spec --error-on-warnings
